# Generated by Django 5.2 on 2025-04-08 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerdata',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_answer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswerdata',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='blog.questiondata'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionlikesdata',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionlikesdata',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_like', to='blog.questiondata'),
        ),
    ]
